export const OBS = {

  INFO_RECOMMENDATIONS_SHOWN: "INFO_RECOMMENDATIONS_SHOWN",
  WARN_SECTION_BLOCKED: "WARN_SECTION_BLOCKED",
  WARN_SECTION_CRASH: "WARN_SECTION_CRASH",
  WARN_ACTION_BLOCKED: "WARN_ACTION_BLOCKED",
  WARN_SAFE_MODE_WRITE_BLOCKED: "WARN_SAFE_MODE_WRITE_BLOCKED",
  WARN_EXPORT_EMPTY: "WARN_EXPORT_EMPTY",
  WARN_ACTION_EXECUTED: "WARN_ACTION_EXECUTED",
  INFO_WRITE_OK: "INFO_WRITE_OK",
  ERR_ACTION_FAILED: "ERR_ACTION_FAILED",
  AUDIT_CACHE_COPY: "AUDIT_CACHE_COPY",

  AUDIT_CACHE_REFRESH: "AUDIT_CACHE_REFRESH",
} as const;
