export const OBS = {
  WARN_SECTION_BLOCKED: "WARN_SECTION_BLOCKED",
  WARN_SECTION_CRASH: "WARN_SECTION_CRASH",
  WARN_ACTION_BLOCKED: "WARN_ACTION_BLOCKED",
  WARN_EXPORT_EMPTY: "WARN_EXPORT_EMPTY",
  WARN_ACTION_EXECUTED: "WARN_ACTION_EXECUTED",
  ERR_ACTION_FAILED: "ERR_ACTION_FAILED"
} as const;
