export const OBS = {
  WARN_SECTION_BLOCKED: "WARN_SECTION_BLOCKED",
  WARN_SECTION_CRASH: "WARN_SECTION_CRASH",
  WARN_ACTION_BLOCKED: "WARN_ACTION_BLOCKED",
  WARN_EXPORT_EMPTY: "WARN_EXPORT_EMPTY"
} as const;
