export const ERR = {
  KERNEL_BOOT_FAILED: "ERR_KERNEL_BOOT_FAILED",
  CONTRACT_MISSING: "ERR_CONTRACT_MISSING",
  INVALID_CONFIG: "ERR_INVALID_CONFIG",
  UNAUTHORIZED: "ERR_UNAUTHORIZED",
  FORBIDDEN: "ERR_FORBIDDEN",
  NOT_FOUND: "ERR_NOT_FOUND",
  STORAGE_FAILURE: "ERR_STORAGE_FAILURE",
  NETWORK_FAILURE: "ERR_NETWORK_FAILURE",
  EVENT_BUS_FAILURE: "ERR_EVENT_BUS_FAILURE",
  FEATURE_FLAG_INVALID: "ERR_FEATURE_FLAG_INVALID",
  SAFE_RENDER_FAILURE: "ERR_SAFE_RENDER_FAILURE",
  TELEMETRY_FAILURE: "ERR_TELEMETRY_FAILURE",
  POLICY_ENGINE_FAILURE: "ERR_POLICY_ENGINE_FAILURE",
  SAFE_MODE_FAILURE: "ERR_SAFE_MODE_FAILURE"
} as const;

export const WARN = {
  DEGRADED_MODE: "WARN_DEGRADED_MODE",
  FEATURE_FLAG_FALLBACK: "WARN_FEATURE_FLAG_FALLBACK",
  POLICY_DEFAULT: "WARN_POLICY_DEFAULT",
  SAFE_RENDER_RECOVERED: "WARN_SAFE_RENDER_RECOVERED",
  EVENT_DROPPED: "WARN_EVENT_DROPPED",
  TELEMETRY_PARTIAL: "WARN_TELEMETRY_PARTIAL"
} as const;

export const ERR_CODES = Object.values(ERR);
export const WARN_CODES = Object.values(WARN);

export type ErrCode = typeof ERR_CODES[number];
export type WarnCode = typeof WARN_CODES[number];
export type ErrorCode = ErrCode | WarnCode;
