/**
 * Reason Codes Registry - v1
 *
 * Governance intent:
 * - Freeze the reason-code vocabulary for the enforcement critical path.
 * - Any new reason codes in the scanned enforcement surface MUST be added here + RFC.
 *
 * This file is SSOT for reason codes used by: ports/bootstrap/write-gateway/contracts/policy.
 */
export const REASON_CODES_V1 = [
  "ERR_ADAPTER_APPLY",
  "ERR_CODES",
  "ERR_CONTRACT_MISSING",
  "ERR_CP_ENFORCEMENT_DEPS_NOT_REGISTERED",
  "ERR_CP_TOGGLE_NOT_ADMIN",
  "ERR_DISABLED",
  "ERR_EVENT_BUS_FAILURE",
  "ERR_FEATURE_FLAG_INVALID",
  "ERR_FORBIDDEN",
  "ERR_INVALID_CONFIG",
  "ERR_KERNEL_BOOT_FAILED",
  "ERR_MODULE_DISABLED",
  "ERR_NETWORK_FAILURE",
  "ERR_NOT_FOUND",
  "ERR_POLICY_DENY",
  "ERR_POLICY_DENY_DEFAULT",
  "ERR_POLICY_DENY_DISABLED",
  "ERR_POLICY_DENY_ROLE",
  "ERR_POLICY_ENGINE_FAILURE",
  "ERR_POLICY_EVAL",
  "ERR_SAFE_MODE_DENY_NON_CP",
  "ERR_SAFE_MODE_FAILURE",
  "ERR_SAFE_RENDER_FAILURE",
  "ERR_STORAGE_FAILURE",
  "ERR_TELEMETRY_FAILURE",
  "ERR_UNAUTHORIZED",
  "ERR_WRITE_CMD_CORRELATION_REQUIRED",
  "ERR_WRITE_CMD_KIND_REQUIRED",
  "ERR_WRITE_CMD_TENANT_REQUIRED",
  "ERR_WRITE_UNKNOWN",
  "OK_CP_TOGGLE_ADMIN",
  "OK_ENABLED",
  "OK_NOT_CONFIGURED",
  "OK_POLICY_ALLOW",
  "OK_SAFE_MODE_CP_ALLOW",
  "WARN_CODES",
  "WARN_DEGRADED_MODE",
  "WARN_EVENT_DROPPED",
  "WARN_FEATURE_FLAG_FALLBACK",
  "WARN_POLICY_DEFAULT",
  "WARN_SAFE_RENDER_RECOVERED",
  "WARN_TELEMETRY_PARTIAL",
] as const;

export type ReasonCodeV1 = (typeof REASON_CODES_V1)[number];
