/**
 * Reason Codes Registry - v1
 *
 * Governance intent:
 * - Freeze the reason-code vocabulary for the enforcement critical path.
 * - Any new reason codes in the scanned enforcement surface MUST be added here + RFC.
 *
 * This file is SSOT for reason codes used by: ports/bootstrap/write-gateway/contracts/policy.
 */
export const REASON_CODES_V1 = [
            "ERR_ACTOR_ID_MISSING",
  "ERR_ADAPTER_APPLY",
  "ERR_BILLING_BIND_FAILED",
  "ERR_BILLING_EVENT_ID_REQUIRED",
  "ERR_BILLING_HOOK_FAILED",
  "ERR_BILLING_NOT_CONFIGURED",
  "ERR_BILLING_SINK_EMIT_FAILED",
  "ERR_CAPABILITY_DISABLED",
  "ERR_CODES",
  "ERR_CONTRACT_MISSING",
  "ERR_CP_ENFORCEMENT_DEPS_NOT_REGISTERED",
  "ERR_CP_SURFACE_REGISTRY_EMPTY",
  "ERR_CP_TOGGLE_NOT_ADMIN",
  "ERR_DEFAULT_ENTITLEMENTS_FAILED",
  "ERR_DISABLED",
  "ERR_EVENT_BUS_FAILURE",
  "ERR_FEATURE_FLAG_INVALID",
  "ERR_FORBIDDEN",
  "ERR_INVALID_CONFIG",
  "ERR_KERNEL_BOOT_FAILED",
  "ERR_MODULE_CATALOG_INVALID",
  "ERR_MODULE_CATALOG_MISSING",
  "ERR_MODULE_DISABLED",
  "ERR_NETWORK_FAILURE",
  "ERR_NOT_FOUND",
  "ERR_ONBOARDING_PERSIST_FAILED",
  "ERR_ONBOARDING_ROLLBACK_FAILED",
  "ERR_ONBOARDING_SNAPSHOT_FAILED",
  "ERR_PAGE_DISABLED",
  "ERR_POLICY_DENY",
  "ERR_POLICY_DENY_DEFAULT",
  "ERR_POLICY_DENY_DISABLED",
  "ERR_POLICY_DENY_ROLE",
  "ERR_POLICY_ENGINE_FAILURE",
  "ERR_POLICY_EVAL",
  "ERR_RUNTIME_IDENTITY_UNAVAILABLE",
  "ERR_SAFE_MODE_DENY_NON_CP",
  "ERR_SAFE_MODE_FAILURE",
  "ERR_SAFE_RENDER_FAILURE",
  "ERR_SNAPSHOT_FAILED",
  "ERR_SNAPSHOT_NOT_BOUND",
  "ERR_STORAGE_FAILURE",
  "ERR_TELEMETRY_FAILURE",
  "ERR_TENANT_ALREADY_EXISTS",
  "ERR_TENANT_ID_MISSING",
  "ERR_TENANT_KEY_INVALID",
  "ERR_TENANT_ONBOARDING_FAILED",
  "ERR_TENANT_ONBOARDING_INVALID_INPUT",
  "ERR_TENANT_ONBOARDING_ORCHESTRATOR_EVENT_UNKNOWN",
  "ERR_TENANT_ONBOARDING_ORCHESTRATOR_NOT_STARTED",
  "ERR_UNAUTHORIZED",
  "ERR_VFS_NOT_BOUND",
  "ERR_VFS_NOT_FOUND",
  "ERR_VFS_READ_FAILED",
  "ERR_VFS_WRITE_FAILED",
  "ERR_WRITE_CMD_CORRELATION_REQUIRED",
  "ERR_WRITE_CMD_KIND_REQUIRED",
  "ERR_WRITE_CMD_TENANT_REQUIRED",
  "ERR_WRITE_UNKNOWN",
  "OK_CP_TOGGLE_ADMIN",
  "OK_ENABLED",
  "OK_POLICY_ALLOW",
  "OK_SAFE_MODE_CP_ALLOW",
  "WARN_CODES",
  "WARN_DEGRADED_MODE",
  "WARN_EVENT_DROPPED",
  "WARN_FEATURE_FLAG_FALLBACK",
  "WARN_POLICY_DEFAULT",
  "WARN_SAFE_RENDER_RECOVERED",
  "WARN_SNAPSHOT_BEGIN_FAILED",
  "WARN_SNAPSHOT_COMMIT_FAILED",
  "WARN_TELEMETRY_PARTIAL",





] as const;


// ---- Foundation shim: keep legacy type names stable (minimal, no behavior change)
export type ReasonCodeV1 = typeof REASON_CODES_V1[keyof typeof REASON_CODES_V1];
export type ReasonCode = ReasonCodeV1;
